<?php


namespace EricksonReyes\DomainDrivenDesign\ValueObject;

/**
 * Class CurrencyCodes
 * @package EricksonReyes\DomainDrivenDesign\ValueObject
 */
class CurrencyCodes
{

    /**
     * @param string $aCurrencyCode
     * @return bool
     */
    public static function has(string $aCurrencyCode): bool {
        return in_array($aCurrencyCode, self::validCurrencyCodes());
    }

    /**
     * @param string $aCurrencyCode
     * @return bool
     */
    public static function doesNotHave(string $aCurrencyCode): bool {
        return !self::has($aCurrencyCode);
    }

    /**
     * @return array
     */
    private static function validCurrencyCodes(): array
    {
        return [
            'AFN',
            'ALL',
            'DZD',
            'USD',
            'EUR',
            'AOA',
            'XCD',
            'ARS',
            'AMD',
            'AWG',
            'AUD',
            'AZN',
            'BSD',
            'BHD',
            'BDT',
            'BBD',
            'BYR',
            'BZD',
            'XOF',
            'BMD',
            'BTN',
            'BOB',
            'BAM',
            'BWP',
            'NOK',
            'BRL',
            'BND',
            'BGN',
            'BIF',
            'KHR',
            'XAF',
            'CAD',
            'CVE',
            'KYD',
            'CLP',
            'CNY',
            'HKD',
            'COP',
            'KMF',
            'CDF',
            'NZD',
            'CRC',
            'HRK',
            'CUP',
            'CZK',
            'DKK',
            'DJF',
            'DOP',
            'ECS',
            'EGP',
            'SVC',
            'ERN',
            'ETB',
            'FKP',
            'FJD',
            'GMD',
            'GEL',
            'GHS',
            'GIP',
            'QTQ',
            'GGP',
            'GNF',
            'GWP',
            'GYD',
            'HTG',
            'HNL',
            'HUF',
            'ISK',
            'INR',
            'IDR',
            'IRR',
            'IQD',
            'GBP',
            'ILS',
            'JMD',
            'JPY',
            'JOD',
            'KZT',
            'KES',
            'KPW',
            'KRW',
            'KWD',
            'KGS',
            'LAK',
            'LBP',
            'LSL',
            'LRD',
            'LYD',
            'CHF',
            'MKD',
            'MGF',
            'MWK',
            'MYR',
            'MVR',
            'MRO',
            'MUR',
            'MXN',
            'MDL',
            'MNT',
            'MAD',
            'MZN',
            'MMK',
            'NAD',
            'NPR',
            'ANG',
            'XPF',
            'NIO',
            'NGN',
            'OMR',
            'PKR',
            'PAB',
            'PGK',
            'PYG',
            'PEN',
            'PHP',
            'PLN',
            'QAR',
            'RON',
            'RUB',
            'RWF',
            'SHP',
            'WST',
            'STD',
            'SAR',
            'RSD',
            'SCR',
            'SLL',
            'SGD',
            'SBD',
            'SOS',
            'ZAR',
            'SSP',
            'LKR',
            'SDG',
            'SRD',
            'SZL',
            'SEK',
            'SYP',
            'TWD',
            'TJS',
            'TZS',
            'THB',
            'TOP',
            'TTD',
            'TND',
            'TRY',
            'TMT',
            'UGX',
            'UAH',
            'AED',
            'UYU',
            'UZS',
            'VUV',
            'VEF',
            'VND',
            'YER',
            'ZMW',
            'ZWD',
            'BYN',
            'CUC',
            'GTQ',
            'MGA',
            'MOP',
            'MRU',
            'STN',
            'VES'
        ];
    }
}